version: '3'

services:

  lending-page:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:80"
    deploy:
      mode: replicated
      replicas: 1